- type: department
  id: Royalty
  description: department-royalty-description
  color: "#701442"
  weight: 200
  roles:
    - King
    - Queen
    - Bishop
    - LordCommanderOfTheKingsguard
    - Hand

- type: department
  id: Kingsguard
  description: department-kingsguard-description
  color: "#701442"
  weight: 199
  roles:
    - LordCommanderOfTheKingsguard
    - Guard
    - Knight

- type: department
  id: Clergy
  description: department-clergy-description
  color: "#701442"
  weight: 198
  roles:
    - Bishop
    - Chaplain
    - Nun
    - Alchemist

- type: department
  id: Market
  description: department-market-description
  color: "#701442"
  weight: 197
  roles:
    - Treasurer

- type: department
  id: Civil
  description: department-civil-description
  color: "#701442"
  weight: 197
  roles:
    - Executioner
