- type: department
  id: Royalty
  description: department-royalty-description
  color: "#701442"
  weight: 200
  roles:
    - King
    - Queen
    - Bishop
    - LordCommanderOfTheKingsguard
    - Hand

- type: department
  id: Kingsguard
  description: department-kingsguard-description
  color: "#701442"
  weight: 199
  roles:
    - LordCommanderOfTheKingsguard
    - Guard

- type: department
  id: Clergy
  description: department-clergy-description
  color: "#701442"
  weight: 199
  roles:
    - Bishop
    - Chaplain
    - Nun
